package media

import (
	"context"
	"io"
	"os/exec"
	"time"
)

// Runner must honor cancellation and reap its child before returning. Arguments
// are generated by Tools, never shell commands or client-supplied FFmpeg options.
type Runner interface {
	Run(context.Context, string, []string, io.Writer) error
}
type ExecRunner struct{}

func (ExecRunner) Run(ctx context.Context, executable string, args []string, output io.Writer) error {
	cmd := exec.CommandContext(ctx, executable, args...)
	cmd.Stdout, cmd.Stderr = output, io.Discard
	cmd.WaitDelay = time.Second
	return cmd.Run()
}
