wireplumber.profiles = {
    main = {
        monitor.alsa = disabled
        monitor.bluez = disabled
        monitor.bluez-midi = disabled
        monitor.v4l2 = disabled
        support.portal-permissionstore = disabled
    }
}
