// Package server exposes the versioned client protocol. Provider DTOs stay inside provider adapters.
package server

import (
	"net/http"

	"zombiebox.local/gateway/internal/domain"
)

func (s *Server) routes() {
	s.mux.HandleFunc("POST /v1/device/companions/invitations", s.auth(s.companionInvite))
	s.mux.HandleFunc("GET /v1/device/companions", s.auth(s.companionPending))
	s.mux.HandleFunc("POST /v1/device/companions/{request}/decision", s.auth(s.companionDecision))
	s.mux.HandleFunc("DELETE /v1/device/companions/{grant}", s.auth(s.companionRevoke))
	s.mux.HandleFunc("POST /v1/device/remote/poll", s.auth(s.companionPoll))
	s.mux.HandleFunc("POST /v1/device/remote/ack", s.auth(s.companionAck))
	s.mux.HandleFunc("POST /v1/companion/join", s.companionJoin)
	s.mux.HandleFunc("GET /v1/companion/targets", s.companionTargets)
	s.mux.HandleFunc("POST /v1/companion/requests/{request}", s.companionRequest)
	s.mux.HandleFunc("POST /v1/companion/proof", s.companionProof)
	s.mux.HandleFunc("GET /v1/companion/status", s.companionAuth(s.companionStatus))
	s.mux.HandleFunc("POST /v1/companion/commands", s.companionAuth(s.companionCommand))
	s.mux.HandleFunc("DELETE /v1/companion/session", s.companionAuth(s.companionForget))
	s.mux.HandleFunc("GET /v1/companion/media/queue", s.companionAuth(s.companionQueue))
	s.mux.HandleFunc("POST /v1/companion/media/queue", s.companionAuth(s.companionQueue))
	s.mux.HandleFunc("DELETE /v1/companion/media/queue", s.companionAuth(s.companionQueue))
	s.mux.HandleFunc("GET /v1/companion/media", s.companionAuth(s.companionMediaStatus))
	s.mux.HandleFunc("PUT /v1/companion/media/{media}", s.companionAuth(s.companionMediaUpload))
	s.mux.HandleFunc("POST /v1/companion/media/{media}/play", s.companionAuth(s.companionMediaPlay))
	s.mux.HandleFunc("DELETE /v1/companion/media/{media}", s.companionAuth(s.companionMediaDelete))
	s.mux.HandleFunc("POST /v1/companion/cast", s.companionAuth(s.companionCast))
	for _, pattern := range []string{"PUT /v1/companion/cast/{cast}", "DELETE /v1/companion/cast/{cast}", "POST /v1/companion/cast/{cast}/ready"} {
		s.mux.HandleFunc(pattern, s.companionAuth(s.companionCastOperation))
	}

	s.mux.HandleFunc("GET /v1/search", s.auth(s.globalSearch))
	s.mux.HandleFunc("GET /v1/youtube/account", s.auth(s.youtubeAccountStatus))
	s.mux.HandleFunc("POST /v1/youtube/account/authorization", s.auth(s.youtubeAccountStart))
	s.mux.HandleFunc("POST /v1/youtube/account/authorization/poll", s.auth(s.youtubeAccountPoll))
	s.mux.HandleFunc("DELETE /v1/youtube/account", s.auth(s.youtubeAccountDisconnect))
	s.mux.HandleFunc("GET /v1/youtube/account/{list}", s.auth(s.youtubeAccountList))
	s.mux.HandleFunc("GET /v1/youtube/related", s.auth(s.youtubeRelated))
	s.mux.HandleFunc("GET /v1/youtube/related/{video}", s.auth(s.youtubeRelated))
	s.mux.HandleFunc("GET /v1/network/sample", s.auth(s.networkDownload))
	s.mux.HandleFunc("POST /v1/device/network", s.auth(s.networkReport))
	for _, method := range []string{"GET", "PUT", "DELETE"} {
		s.mux.HandleFunc(method+" /v1/media-receiver", s.auth(s.mediaReceiver))
	}
	s.mux.HandleFunc("POST /v1/youtube/receiver", s.auth(s.startYouTubeReceiver))
	s.mux.HandleFunc("GET /v1/youtube/receiver/{receiver}", s.auth(s.youTubeReceiverOperation))
	s.mux.HandleFunc("POST /v1/youtube/receiver/{receiver}/state", s.auth(s.youTubeReceiverOperation))
	s.mux.HandleFunc("DELETE /v1/youtube/receiver/{receiver}", s.auth(s.youTubeReceiverOperation))
	s.mux.HandleFunc("GET /v1/artwork/{item}", s.auth(s.artwork))
	s.mux.HandleFunc("GET /v1/probes", s.auth(s.probeManifest))
	s.mux.HandleFunc("GET /v1/probes/{probe}", s.probeStream)
	s.mux.HandleFunc("GET /v1/cast/receivers", s.auth(s.castReceivers))
	s.mux.HandleFunc("POST /v1/cast", s.auth(s.createCast))
	s.mux.HandleFunc("GET /v1/cast/active", s.auth(s.activeCast))
	s.mux.HandleFunc("DELETE /v1/cast/queue", s.auth(s.stopReceiverQueue))
	s.mux.HandleFunc("PUT /v1/cast/{cast}", s.auth(s.castLease))
	s.mux.HandleFunc("POST /v1/cast/{cast}/ready", s.auth(s.castReady))
	s.mux.HandleFunc("DELETE /v1/cast/{cast}", s.auth(s.stopCast))
	s.mux.HandleFunc("POST /internal/relay/auth", s.relayAuth)
	s.mux.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) { respond(w, 200, Health{"ok", 1}) })
	s.mux.HandleFunc("POST /v1/devices/register", s.register)
	s.mux.HandleFunc("GET /v1/device", s.auth(func(w http.ResponseWriter, r *http.Request, d domain.Device) { respond(w, 200, d) }))
	s.mux.HandleFunc("PUT /v1/device/client", s.auth(s.clientVersion))
	s.mux.HandleFunc("GET /v1/device/preferences", s.auth(func(w http.ResponseWriter, r *http.Request, d domain.Device) { respond(w, 200, d.Preferences) }))
	s.mux.HandleFunc("PUT /v1/device/preferences", s.auth(s.preferences))
	s.mux.HandleFunc("PUT /v1/device/hardware", s.auth(s.hardwareReport))
	s.mux.HandleFunc("PUT /v1/device/capabilities", s.auth(s.capabilities))
	s.mux.HandleFunc("GET /v1/modules", s.auth(s.modules))
	s.mux.HandleFunc("GET /v1/diagnostics", s.auth(s.diagnostics))
	s.mux.HandleFunc("GET /v1/catalog", s.auth(s.catalogPage))
	s.mux.HandleFunc("PUT /v1/iptv/favorites/{item}", s.auth(s.iptvFavorite))
	s.mux.HandleFunc("DELETE /v1/iptv/favorites/{item}", s.auth(s.iptvFavorite))
	s.mux.HandleFunc("GET /v1/browse", s.auth(s.browsePage))
	s.mux.HandleFunc("GET /v1/home", s.auth(s.home))
	s.mux.HandleFunc("GET /v1/events", s.auth(s.poll))
	s.mux.HandleFunc("GET /v1/integrations", s.auth(s.integrationList))
	s.mux.HandleFunc("POST /v1/browser", s.auth(s.startBrowser))
	s.mux.HandleFunc("GET /v1/browser/{browser}/frame", s.auth(s.browserOperation))
	s.mux.HandleFunc("POST /v1/browser/{browser}/input", s.auth(s.browserOperation))
	s.mux.HandleFunc("DELETE /v1/browser/{browser}", s.auth(s.browserOperation))
	s.mux.HandleFunc("GET /v1/player/spotify", s.auth(s.nowPlaying))
	s.mux.HandleFunc("GET /v1/player/spotify/authorization", s.auth(s.spotifyAuthorization))
	s.mux.HandleFunc("GET /v1/airplay/pairing", s.auth(s.airplayPairing))
	s.mux.HandleFunc("POST /v1/player/spotify", s.auth(s.playerCommand))
	s.mux.HandleFunc("POST /v1/player/airplay", s.auth(s.airplayPlayerCommand))
	s.mux.HandleFunc("GET /v1/providers", s.auth(s.providers))
	s.mux.HandleFunc("PUT /v1/providers/{provider}", s.auth(s.configureProvider))
	s.mux.HandleFunc("POST /v1/playback", s.auth(s.playback))
	s.mux.HandleFunc("POST /v1/playback/{session}/adapt", s.auth(s.adaptPlayback))
	s.mux.HandleFunc("PUT /v1/playback/{session}/progress", s.auth(s.progress))
	s.mux.HandleFunc("DELETE /v1/playback/{session}", s.auth(s.stop))
	s.mux.HandleFunc("GET /v1/playback/{session}/tracks", s.auth(s.playbackTracks))
	s.mux.HandleFunc("POST /v1/playback/{session}/audio", s.auth(s.selectAudio))
	s.mux.HandleFunc("GET /v1/playback/{session}/qualities", s.auth(s.playbackQualities))
	s.mux.HandleFunc("POST /v1/playback/{session}/quality", s.auth(s.selectQuality))
	s.mux.HandleFunc("GET /v1/playback/{session}/subtitles/{track}", s.auth(s.playbackSubtitles))
	s.mux.HandleFunc("GET /v1/streams/{session}", s.stream)
	s.mux.HandleFunc("GET /v1/streams/{session}/{resource}", s.stream)
}
